/**
 * Loop n Love - Authoritative Verified Product Catalogue Data
 * Extracted from Bouquet(3).pdf and hair.pdf
 *
 * MAPPING VERIFICATION:
 * - 13 Bouquets (Bouquet 01 to Bouquet 13) sorted top-to-bottom per PDF page
 * - 7 Hair Accessories (Hair Accessory 01 to Hair Accessory 07) sorted top-to-bottom per PDF page
 * - Strictly matches provided price lists & photos
 */

export const INITIAL_PRODUCTS = [
  // ==========================================
  // CROCHET FLOWERS & BOUQUETS (13 ITEMS)
  // ==========================================
  {
    id: 'bouquet-01',
    name: 'Bouquet 01',
    category: 'Crochet Flowers & Bouquets',
    price: 199,
    image: 'assets/product-images/bouquet_01.jpg',
    images: ['assets/product-images/bouquet_01.jpg'],
    description: 'Handcrafted single crochet flower bouquet in a rich royal blue shade, wrapped in crisp white paper with a matching blue satin ribbon.',
    inStock: true,
    stockQuantity: 10,
    featured: true,
    isNewArrival: false,
    pdfPage: 1,
    customizable: true
  },
  {
    id: 'bouquet-02',
    name: 'Bouquet 02',
    category: 'Crochet Flowers & Bouquets',
    price: 399,
    image: 'assets/product-images/bouquet_02.jpg',
    images: ['assets/product-images/bouquet_02.jpg'],
    description: 'Charming pastel pink crochet roses with delicate bud accents, wrapped in rustic mesh burlap and finished with a soft blush ribbon and heart tag.',
    inStock: true,
    stockQuantity: 8,
    featured: true,
    isNewArrival: false,
    pdfPage: 1,
    customizable: true
  },
  {
    id: 'bouquet-03',
    name: 'Bouquet 03',
    category: 'Crochet Flowers & Bouquets',
    price: 399,
    image: 'assets/product-images/bouquet_03.jpg',
    images: ['assets/product-images/bouquet_03.jpg'],
    description: 'Trio of handmade soft pink crochet roses wrapped in natural jute burlap, accented with a sky blue ribbon and a miniature crochet heart keepsake.',
    inStock: true,
    stockQuantity: 8,
    featured: false,
    isNewArrival: true,
    pdfPage: 2,
    customizable: true
  },
  {
    id: 'bouquet-04',
    name: 'Bouquet 04',
    category: 'Crochet Flowers & Bouquets',
    price: 299,
    image: 'assets/product-images/bouquet_04.jpg',
    images: ['assets/product-images/bouquet_04.jpg'],
    description: 'Handmade cream rose paired with a vibrant red crochet heart topper, wrapped in two-tone white and red paper with a bold red satin ribbon.',
    inStock: true,
    stockQuantity: 12,
    featured: false,
    isNewArrival: false,
    pdfPage: 3,
    customizable: true
  },
  {
    id: 'bouquet-05',
    name: 'Bouquet 05',
    category: 'Crochet Flowers & Bouquets',
    price: 699,
    image: 'assets/product-images/bouquet_05.jpg',
    images: ['assets/product-images/bouquet_05.jpg'],
    description: 'Vibrant red crochet roses and deep green leaves arranged in an elegant black-and-gold luxury wrap, tied with a golden satin ribbon.',
    inStock: true,
    stockQuantity: 6,
    featured: true,
    isNewArrival: false,
    pdfPage: 3,
    customizable: true
  },
  {
    id: 'bouquet-06',
    name: 'Bouquet 06',
    category: 'Crochet Flowers & Bouquets',
    price: 999,
    image: 'assets/product-images/bouquet_06.jpg',
    images: ['assets/product-images/bouquet_06.jpg'],
    description: 'Generous cluster of deep red crochet roses nestled closely in matte black packaging and tied with a clean white bow. A grand romantic keepsake.',
    inStock: true,
    stockQuantity: 5,
    featured: true,
    isNewArrival: false,
    pdfPage: 4,
    customizable: true
  },
  {
    id: 'bouquet-07',
    name: 'Bouquet 07',
    category: 'Crochet Flowers & Bouquets',
    price: 899,
    image: 'assets/product-images/bouquet_07.jpg',
    images: ['assets/product-images/bouquet_07.jpg'],
    description: 'Deluxe red crochet roses accented with delicate floral filler, wrapped in translucent black layered paper with ribbon. An exquisite handcrafted centerpiece.',
    inStock: true,
    stockQuantity: 5,
    featured: true,
    isNewArrival: true,
    pdfPage: 4,
    customizable: true
  },
  {
    id: 'bouquet-08',
    name: 'Bouquet 08',
    category: 'Crochet Flowers & Bouquets',
    price: 399,
    image: 'assets/product-images/bouquet_08.jpg',
    images: ['assets/product-images/bouquet_08.jpg'],
    description: 'Trio of cheerful handmade crochet daisies with bright yellow centers and fresh green leaves, wrapped in warm kraft paper with a pastel pink bow.',
    inStock: true,
    stockQuantity: 10,
    featured: false,
    isNewArrival: true,
    pdfPage: 5,
    customizable: true
  },
  {
    id: 'bouquet-09',
    name: 'Bouquet 09',
    category: 'Crochet Flowers & Bouquets',
    price: 499,
    image: 'assets/product-images/bouquet_09.jpg',
    images: ['assets/product-images/bouquet_09.jpg'],
    description: 'Sweet bouquet featuring 4 puffy pink crochet hearts and mini daisies wrapped in soft translucent pink paper with branded satin ribbons.',
    inStock: true,
    stockQuantity: 8,
    featured: false,
    isNewArrival: true,
    pdfPage: 5,
    customizable: true
  },
  {
    id: 'bouquet-10',
    name: 'Bouquet 10',
    category: 'Crochet Flowers & Bouquets',
    price: 599,
    image: 'assets/product-images/bouquet_10.jpg',
    images: ['assets/product-images/bouquet_10.jpg'],
    description: 'Handmade crochet sunflower with friendly crochet bumblebee, daisies, and buds in a soft blush pink wrap tied with a pure white ribbon.',
    inStock: true,
    stockQuantity: 7,
    featured: true,
    isNewArrival: true,
    pdfPage: 6,
    customizable: true
  },
  {
    id: 'bouquet-11',
    name: 'Bouquet 11',
    category: 'Crochet Flowers & Bouquets',
    price: 449,
    image: 'assets/product-images/bouquet_11.jpg',
    images: ['assets/product-images/bouquet_11.jpg'],
    description: 'Trio of graceful lavender crochet tulips accented with small white florets, wrapped in matching purple paper with a silky ribbon.',
    inStock: true,
    stockQuantity: 9,
    featured: false,
    isNewArrival: false,
    pdfPage: 6,
    customizable: true
  },
  {
    id: 'bouquet-12',
    name: 'Bouquet 12',
    category: 'Crochet Flowers & Bouquets',
    price: 449,
    image: 'assets/product-images/bouquet_12.jpg',
    images: ['assets/product-images/bouquet_12.jpg'],
    description: 'Sunny yellow crochet tulips with white blossom accents, wrapped in delicate layered neutral paper with a silver-white bow.',
    inStock: true,
    stockQuantity: 8,
    featured: false,
    isNewArrival: false,
    pdfPage: 7,
    customizable: true
  },
  {
    id: 'bouquet-13',
    name: 'Bouquet 13',
    category: 'Crochet Flowers & Bouquets',
    price: 149,
    image: 'assets/product-images/bouquet_13.jpg',
    images: ['assets/product-images/bouquet_13.jpg'],
    description: 'Single stem handcrafted pink crochet tulip with leafy stem, wrapped in soft rose-pink paper and tied with a gold ribbon. A sweet, thoughtful gesture.',
    inStock: true,
    stockQuantity: 15,
    featured: false,
    isNewArrival: true,
    pdfPage: 7,
    customizable: true
  },

  // ==========================================
  // HAIR ACCESSORIES (7 ITEMS)
  // ==========================================
  {
    id: 'hair-01',
    name: 'Hair Accessory 01',
    category: 'Hair Accessories',
    price: 249,
    image: 'assets/product-images/hair_01.jpg',
    images: ['assets/product-images/hair_01.jpg'],
    description: 'Delicate handmade crochet flower hair piece featuring layered petals and flowing white crochet garland tassels with pink tips.',
    inStock: true,
    stockQuantity: 12,
    featured: true,
    isNewArrival: true,
    pdfPage: 1,
    customizable: true
  },
  {
    id: 'hair-02',
    name: 'Hair Accessory 02',
    category: 'Hair Accessories',
    price: 149,
    image: 'assets/product-images/hair_02.jpg',
    images: ['assets/product-images/hair_02.jpg'],
    description: 'Handcrafted rose crochet hair clip with twin white crochet tassel drops, offering an elegant traditional touch.',
    inStock: true,
    stockQuantity: 15,
    featured: false,
    isNewArrival: false,
    pdfPage: 1,
    customizable: true
  },
  {
    id: 'hair-03',
    name: 'Hair Accessory 03',
    category: 'Hair Accessories',
    price: 199,
    image: 'assets/product-images/hair_03.jpg',
    images: ['assets/product-images/hair_03.jpg'],
    description: 'Vintage-inspired crochet floral head bandana / kerchief in soft cream with dainty pastel pink flowers and green leaf accents.',
    inStock: true,
    stockQuantity: 10,
    featured: true,
    isNewArrival: true,
    pdfPage: 2,
    customizable: true
  },
  {
    id: 'hair-04',
    name: 'Hair Accessory 04',
    category: 'Hair Accessories',
    price: 99,
    image: 'assets/product-images/hair_04.jpg',
    images: ['assets/product-images/hair_04.jpg'],
    description: 'Classic handcrafted red crochet bow hair clip made with soft milk cotton yarn. Perfect for half-up hairstyles.',
    inStock: true,
    stockQuantity: 20,
    featured: false,
    isNewArrival: false,
    pdfPage: 2,
    customizable: true
  },
  {
    id: 'hair-05',
    name: 'Hair Accessory 05',
    category: 'Hair Accessories',
    price: 149,
    image: 'assets/product-images/hair_05.jpg',
    images: ['assets/product-images/hair_05.jpg'],
    description: 'Adorable handcrafted twin strawberry crochet hair tie with white bow detail. Charming and lightweight.',
    inStock: true,
    stockQuantity: 15,
    featured: true,
    isNewArrival: false,
    pdfPage: 3,
    customizable: true
  },
  {
    id: 'hair-06',
    name: 'Hair Accessory 06',
    category: 'Hair Accessories',
    price: 99,
    image: 'assets/product-images/hair_06.jpg',
    images: ['assets/product-images/hair_06.jpg'],
    description: 'Cheerful miniature crochet sunflower hair scrunchie / clip with golden yellow petals and warm cocoa center.',
    inStock: true,
    stockQuantity: 20,
    featured: false,
    isNewArrival: true,
    pdfPage: 3,
    customizable: true
  },
  {
    id: 'hair-07',
    name: 'Hair Accessory 07',
    category: 'Hair Accessories',
    price: 149,
    image: 'assets/product-images/hair_07.jpg',
    images: ['assets/product-images/hair_07.jpg'],
    description: 'Graceful lily of the valley crochet hair bow tie with delicate bell blossoms and green leaves. Signature boutique piece.',
    inStock: true,
    stockQuantity: 15,
    featured: true,
    isNewArrival: true,
    pdfPage: 4,
    customizable: true
  }
];

export const CATEGORIES = [
  { name: 'Crochet Flowers & Bouquets', count: 13, available: true },
  { name: 'Hair Accessories', count: 7, available: true },
  { name: 'Custom Keychains', count: 0, available: false },
  { name: 'Crochet Bags', count: 0, available: false },
  { name: 'Keychains', count: 0, available: false }
];
